/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestReaderRouteImport } from './routes/test/reader'
import { Route as TestPdfreaderRouteImport } from './routes/test/pdfreader'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestReaderRoute = TestReaderRouteImport.update({
  id: '/test/reader',
  path: '/test/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const TestPdfreaderRoute = TestPdfreaderRouteImport.update({
  id: '/test/pdfreader',
  path: '/test/pdfreader',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/test/pdfreader': typeof TestPdfreaderRoute
  '/test/reader': typeof TestReaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/test/pdfreader': typeof TestPdfreaderRoute
  '/test/reader': typeof TestReaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/test/pdfreader': typeof TestPdfreaderRoute
  '/test/reader': typeof TestReaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/test/pdfreader' | '/test/reader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/test/pdfreader' | '/test/reader'
  id: '__root__' | '/' | '/login' | '/test/pdfreader' | '/test/reader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TestPdfreaderRoute: typeof TestPdfreaderRoute
  TestReaderRoute: typeof TestReaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/reader': {
      id: '/test/reader'
      path: '/test/reader'
      fullPath: '/test/reader'
      preLoaderRoute: typeof TestReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/pdfreader': {
      id: '/test/pdfreader'
      path: '/test/pdfreader'
      fullPath: '/test/pdfreader'
      preLoaderRoute: typeof TestPdfreaderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TestPdfreaderRoute: TestPdfreaderRoute,
  TestReaderRoute: TestReaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
